# Site settings
title: Kritika Tripathi
description: 'Business Card Page'
url: 'http://developerszeal.com'
baseurl: '/portfolio-site'
profilepic: '/images/kritika.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Kritika Tripathi'
  email: kritika.tripathi@gmail.com
  twitter_username: kritika2807
  github_username:  Kritika
  linkedin_username:  kritika-tripathi-94047968

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
